Repository TopAcademy2022/translator, pull requests merged in 2024-08, with the labels that each got.

#8 Added project files. Closed #1
  translator.sln
  translator/Program.cs
  translator/Translate.cs
  translator/translator.csproj
Labels: enhancement

#11 Added Doxygen documentation. Closed #2
  .gitignore
  Docs/Doxyfile
Labels: documentation, enhancement

#14 Added method find translate for word. Closed #7
  translator/Translate.cs
Labels: documentation, enhancement

#16 Added method delete word from dictionary. Closed #6
  translator/Translate.cs
Labels: documentation, enhancement

#19 Added method load dictionary to file. Closed #15
  translator/Translate.cs
Labels: documentation, enhancement

#20 Added method save dictionary to file. Closed #13
  translator/Translate.cs
Labels: documentation, enhancement

#22 Added method creating file. Closed #3
  translator/Translate.cs
Labels: enhancement

#23 Added display all words. Closed #17
  translator/Translate.cs
Labels: documentation, enhancement

#24 Added testing. Closed #12
  Tests/translator.Tests/TranslateTests.cs
  Tests/translator.Tests/translator.Tests.csproj
  translator.sln
Labels: enhancement

#32 Refactoring Translate class. Closed #31
  translator/Translate.cs
  translator/translator.csproj
Labels: documentation, enhancement

#34 Added Github action. Closed #33
  .github/workflows/dotnet.yml
Labels: enhancement, testing
