Repository TopAcademy2022/translator, pull requests merged in 2025-04, with the labels that each got.

#45 Updated DeleteWordTest method. Closed #43
  Tests/translator.Tests/TranslateTests.cs
Labels: testing

#46 Added test for Createfile method. Closed #25
  Tests/translator.Tests/TranslateTests.cs
  translator/Translate.cs
Labels: documentation, testing

#54 Added export word to out file. Closed #18
  translator/Translate.cs
Labels: enhancement
